// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: event/v1/event.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatId        uint64                 `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatRequest) Reset() {
	*x = ReserveSeatRequest{}
	mi := &file_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatRequest) ProtoMessage() {}

func (x *ReserveSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatRequest.ProtoReflect.Descriptor instead.
func (*ReserveSeatRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveSeatRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ReserveSeatRequest) GetSeatId() uint64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *ReserveSeatRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReserveSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatResponse) Reset() {
	*x = ReserveSeatResponse{}
	mi := &file_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatResponse) ProtoMessage() {}

func (x *ReserveSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatResponse.ProtoReflect.Descriptor instead.
func (*ReserveSeatResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveSeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_event_v1_event_proto protoreflect.FileDescriptor

const file_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x14event/v1/event.proto\x12\bevent.v1\"a\n" +
	"\x12ReserveSeatRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\x04R\x06seatId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\"/\n" +
	"\x13ReserveSeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2Z\n" +
	"\fEventService\x12J\n" +
	"\vReserveSeat\x12\x1c.event.v1.ReserveSeatRequest\x1a\x1d.event.v1.ReserveSeatResponseBTZRgithub.com/Aritiaya50217/High-Concurrency-Ticket-Booking-System/contracts/event/v1b\x06proto3"

var (
	file_event_v1_event_proto_rawDescOnce sync.Once
	file_event_v1_event_proto_rawDescData []byte
)

func file_event_v1_event_proto_rawDescGZIP() []byte {
	file_event_v1_event_proto_rawDescOnce.Do(func() {
		file_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)))
	})
	return file_event_v1_event_proto_rawDescData
}

var file_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_v1_event_proto_goTypes = []any{
	(*ReserveSeatRequest)(nil),  // 0: event.v1.ReserveSeatRequest
	(*ReserveSeatResponse)(nil), // 1: event.v1.ReserveSeatResponse
}
var file_event_v1_event_proto_depIdxs = []int32{
	0, // 0: event.v1.EventService.ReserveSeat:input_type -> event.v1.ReserveSeatRequest
	1, // 1: event.v1.EventService.ReserveSeat:output_type -> event.v1.ReserveSeatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_event_v1_event_proto_init() }
func file_event_v1_event_proto_init() {
	if File_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_v1_event_proto_goTypes,
		DependencyIndexes: file_event_v1_event_proto_depIdxs,
		MessageInfos:      file_event_v1_event_proto_msgTypes,
	}.Build()
	File_event_v1_event_proto = out.File
	file_event_v1_event_proto_goTypes = nil
	file_event_v1_event_proto_depIdxs = nil
}
