version: "3.9"

services:

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    volumes:
      - ./user-service/configs:/app/configs
    env_file:               
      - ./user-service/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always


  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "8081:8081"
    volumes:
      - ./booking-service/configs:/app/configs
    env_file:              
      - ./booking-service/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always


  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    container_name: event-service
    ports:
      - "8082:8082"
    volumes:
      - ./event-service/configs:/app/configs
    env_file:              
      - ./event-service/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:15
    container_name: ticker-booking-system-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123!
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdata: