app:
  name: ${APP_NAME}
  port: ${PORT}

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}
  sslmode: ${DB_SSLMODE}

kafka:
  brokers: ${KAFKA_BROKERS}
  topic_event_created: ${KAFKA_TOPIC_EVENT_CREATED}
  group_id: ${KAFKA_GROUP_ID}

jwt:
  secret: ${JWT_SECRET}
  expire_hours: ${JWT_EXPIRE_HOURS}