name: User Service CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths:
      - 'user-service/**'
      - 'contracts/**'
      - '.github/workflows/user-service.yml'

  pull_request:
    branches: ["main"]
    paths:
      - 'user-service/**'
      - 'contracts/**'
      - '.github/workflows/user-service.yml'

  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test User Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.x"

      - name: Go mod tidy & download
        run: |
          cd user-service
          go mod tidy
          go mod download

      - name: Run unit tests
        run: |
          cd user-service
          go test ./internal/... -v -race

      - name: Build binary
        run: |
          cd user-service
          go build -v -o service ./cmd/server

  docker:
    name: Docker Build & Push User Service
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/high-concurrency-ticket-booking-system-user:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/high-concurrency-ticket-booking-system-user:${{ github.sha }} \
            -f ./user-service/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/high-concurrency-ticket-booking-system-user:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/high-concurrency-ticket-booking-system-user:${{ github.sha }}